// Sibling copy module for FormStatic.tsx — lifted from `lang === "ru" ? … : …`
// ternary chains (Hebrew Localization Phase 4, Task 3).
import type { Locale } from "@/lib/locale";
import { isLocale } from "@/lib/locale";

export const FORM_STATIC_EN = {
  phoneLabel: "Phone",
  nameRequired: "Name is required",
  surnameRequired: "Surname is required",
  phoneRequired: "Phone is required",
  emailInvalid: "Invalid email address",
  emailRequired: "Email is required",
  contactMethodRequired: "What’s the best way to contact you?",
  agreementRequired: "Consent is required",
  agreementOneOf: "Consent required",
  title: "Leave your request and we will contact you shortly",
  nameLabel: "Your name",
  surnameLabel: "Surname",
  emailLabel: "Email",
  contactMethodLegend: "What’s the best way to contact you?",
  phoneCallLabel: "Phone call",
  emailRadioLabel: "Email",
  submitLabel: "Send",
  agreementLead: "I agree with the terms of the ",
  agreementHref: "/privacy-policy",
  agreementLinkLabel: "User agreement",
  agreementTail: " read and accept them",
};

export const FORM_STATIC_COPY: Record<Locale, typeof FORM_STATIC_EN> = {
  en: FORM_STATIC_EN,
  de: {
    phoneLabel: "Telefon",
    nameRequired: "Name ist erforderlich",
    surnameRequired: "Nachname ist erforderlich",
    phoneRequired: "Telefon ist erforderlich",
    emailInvalid: "Ungültige E-Mail Adresse",
    emailRequired: "E-Mail ist erforderlich",
    contactMethodRequired: "Wie können wir Sie am besten kontaktieren?",
    agreementRequired: "Zustimmung erforderlich",
    agreementOneOf: "Einverständnis erforderlich",
    title: "Lassen Sie sich noch heute von uns beraten!",
    nameLabel: "Ihr Vorname",
    surnameLabel: "Ihr Nachname",
    emailLabel: "E-Mail Adresse",
    contactMethodLegend: "Wie möchten Sie am besten kontaktiert werden?",
    phoneCallLabel: "Telefon",
    emailRadioLabel: "E-Mail",
    submitLabel: "Absenden",
    agreementLead: "Ich habe die Bedingungen der ",
    agreementHref: "/de/datenschutzrichtlinie",
    agreementLinkLabel: "Benutzervereinbarung",
    agreementTail: " gelesen und akzeptiere sie",
  },
  pl: {
    phoneLabel: "Telefon",
    nameRequired: "Imię jest wymagane",
    surnameRequired: "Nazwisko jest wymagane",
    phoneRequired: "Telefon jest wymagany",
    emailInvalid: "Nieprawidłowy format email",
    emailRequired: "Email jest wymagany",
    contactMethodRequired: "Wybierz preferowaną formę kontaktu",
    agreementRequired: "Zgoda jest wymagana",
    agreementOneOf: "Wymagane wyrażenie zgody",
    title: "Zostaw zapytanie, a my skontaktujemy się z Tobą wkrótce",
    nameLabel: "Imię",
    surnameLabel: "Nazwisko",
    emailLabel: "E-mail",
    contactMethodLegend: "W jaki sposób najlepiej się z Tobą skontaktować?",
    phoneCallLabel: "Telefonicznie",
    emailRadioLabel: "E-mail",
    submitLabel: "Wyślij",
    agreementLead: "Zgadzam się z ",
    agreementHref: "/pl/polityka-prywatnosci",
    agreementLinkLabel: "Umowa użytkownika",
    agreementTail: " przeczytałem i akceptuję je",
  },
  ru: {
    phoneLabel: "Телефон",
    nameRequired: "Имя обязательно",
    surnameRequired: "Фамилия обязательна",
    phoneRequired: "Телефон обязателен",
    emailInvalid: "Неверный формат email",
    emailRequired: "Email обязателен",
    contactMethodRequired: "Как с вами лучше связаться?",
    agreementRequired: "Согласие обязательно",
    agreementOneOf: "Требуется согласие",
    title: "Оставьте заявку и мы свяжемся с вами в ближайшее время",
    nameLabel: "Ваше имя",
    surnameLabel: "Фамилия",
    emailLabel: "Ваш email",
    contactMethodLegend: "Как с вами лучше связаться?",
    phoneCallLabel: "Телефон",
    emailRadioLabel: "Email",
    submitLabel: "Отправить",
    agreementLead: "Я согласен с ",
    agreementHref: "/ru/politika-privatnosti",
    agreementLinkLabel: "Пользовательским соглашением",
    agreementTail: " прочитал и принимаю их",
  },
  he: FORM_STATIC_EN, // TODO(he)
};

export const formStaticCopy = (lang: string) =>
  FORM_STATIC_COPY[isLocale(lang) ? lang : "en"];
