/* One-off: pull every font the app uses off Google and vendor it into the repo.
 *
 * Why not next/font/local: Google serves one woff2 PER SUBSET, each with its own
 * unicode-range, and next/font/local cannot express unicode-range. Feeding it a
 * single file would either drop Cyrillic and Hebrew or push every visitor the
 * whole multi-script family. So this emits real @font-face rules and carries
 * Google's unicode-range values across unchanged.
 *
 * Weight handling: a variable family is requested as a RANGE (300..500), which
 * returns one file per subset covering every weight in between. A family with no
 * variable cut returns a single-weight face for such a request, and the script
 * falls back to asking for each weight separately — which is what
 * next/font/google did for all of them before.
 *
 * Writes public/fonts/<family>/… and src/app/fonts/vendored.css
 */
import { mkdir, writeFile, rm } from "node:fs/promises";
import { join } from "node:path";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

/* The union of all 77 declarations, read out of the call sites. */
const FAMILIES = [
  { name: "Bodoni Moda",        weights: [400, 500, 600],      italic: true,  subsets: ["latin", "latin-ext"],             extraAxis: "opsz,6..96" },
  { name: "Commissioner",       weights: [300, 400, 500, 600], italic: false, subsets: ["latin", "latin-ext", "cyrillic"] },
  { name: "Cormorant Garamond", weights: [300, 400, 500],      italic: true,  subsets: ["latin", "latin-ext"] },
  { name: "EB Garamond",        weights: [400, 500, 600],      italic: true,  subsets: ["latin", "latin-ext", "cyrillic"] },
  { name: "Forum",              weights: [400],                italic: false, subsets: ["latin", "latin-ext", "cyrillic"] },
  { name: "Frank Ruhl Libre",   weights: [300, 400, 500],      italic: false, subsets: ["hebrew", "latin"] },
  { name: "Fraunces",           weights: [300, 400, 500],      italic: true,  subsets: ["latin", "latin-ext"] },
  { name: "Libre Baskerville",  weights: [400],                italic: false, subsets: ["latin"] },
  { name: "Manrope",            weights: [300, 400, 500, 600], italic: false, subsets: ["latin", "latin-ext", "cyrillic"] },
  { name: "Mulish",             weights: [300, 400, 500, 600, 700], italic: false, subsets: ["latin", "latin-ext", "cyrillic"] },
  { name: "Onest",              weights: [300, 400, 500, 600], italic: false, subsets: ["latin", "latin-ext", "cyrillic"] },
  { name: "Oswald",             weights: [300, 400],           italic: false, subsets: ["latin", "cyrillic"] },
  { name: "Playfair Display",   weights: [400, 500, 600],      italic: true,  subsets: ["latin", "cyrillic"] },
  { name: "Rubik",              weights: [300, 900], italic: false, subsets: ["latin", "cyrillic", "hebrew"] },
  /* 300..900, the family's full variable range, not the 300..600 the union of
     the declarations suggested: [lang]/layout.tsx declares Rubik with NO weight
     at all, and next/font reads that as "the whole range". Narrowing it would
     have turned every real 700+ cut into synthesised bold on the body font of
     the entire site. */
  { name: "Spectral",           weights: [300, 400, 500, 600], italic: false, subsets: ["latin", "latin-ext", "cyrillic"] },
  { name: "Tenor Sans",         weights: [400],                italic: false, subsets: ["latin", "latin-ext", "cyrillic"] },
];

const slug = (s) => s.toLowerCase().replace(/\s+/g, "-");
const famUrl = (n) => encodeURIComponent(n).replace(/%20/g, "+");

function achse(fam, alsBereich) {
  const lo = Math.min(...fam.weights), hi = Math.max(...fam.weights);
  const w = alsBereich && lo !== hi ? `${lo}..${hi}` : fam.weights.join(";");
  const extra = fam.extraAxis ? fam.extraAxis.split(",")[0] + "," : "";
  const extraVal = fam.extraAxis ? fam.extraAxis.split(",")[1] + "," : "";
  if (!fam.italic) return `${extra}wght@${extraVal}${w}`;
  return `ital,${extra}wght@${fam.weights.map(() => "").length ? "" : ""}0,${extraVal}${w};1,${extraVal}${w}`;
}

async function css(fam, alsBereich) {
  const url = `https://fonts.googleapis.com/css2?family=${famUrl(fam.name)}:${achse(fam, alsBereich)}&display=swap`;
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) return null;
  return res.text();
}

const bloecke = (text) => {
  const out = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi;
  let m;
  while ((m = re.exec(text))) out.push({ subset: m[1], regel: m[2] });
  return out;
};

await rm(join("public", "fonts"), { recursive: true, force: true });

const bericht = [];
let cssOut = `/* GENERATED by scripts/tmp-fetch-fonts.mjs — do not edit by hand.
   Self-hosted copies of every Google font this app uses.

   Builds used to fetch these from fonts.googleapis.com at BUILD time, so a build
   machine that could not reach that host could not ship at all — which is what
   happened on 2026-09-27: six attempts, each dying on a different layout's font
   request, while the same URL answered in 0.19s from a laptop. These are
   Google's own woff2 files with their unicode-range values intact. */\n\n`;

for (const fam of FAMILIES) {
  let text = await css(fam, true);
  let variabel = !!text && /font-weight:\s*\d+\s+\d+/.test(text);
  if (!text || (!variabel && fam.weights.length > 1)) {
    const fallback = await css(fam, false);
    if (fallback) { text = fallback; variabel = false; }
  }
  if (!text) { bericht.push({ familie: fam.name, fehler: "CSS nicht erhalten" }); continue; }

  const gewollt = bloecke(text).filter((b) => fam.subsets.includes(b.subset));
  const dir = join("public", "fonts", slug(fam.name));
  await mkdir(dir, { recursive: true });

  let n = 0, bytes = 0;
  for (const b of gewollt) {
    const u = b.regel.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    if (!u) continue;
    const st = (b.regel.match(/font-style:\s*([a-z]+)/i) || [, "normal"])[1];
    const wt = (b.regel.match(/font-weight:\s*([\d ]+)/i) || [, "400"])[1].replace(/\s+/g, "-");
    const datei = `${b.subset}-${st}-${wt}.woff2`;
    const r = await fetch(u[1], { headers: { "User-Agent": UA } });
    if (!r.ok) { bericht.push({ familie: fam.name, fehler: `woff2 ${r.status}` }); continue; }
    const buf = Buffer.from(await r.arrayBuffer());
    await writeFile(join(dir, datei), buf);
    n++; bytes += buf.length;
    cssOut += `/* ${fam.name} · ${b.subset} · ${st} · ${wt} */\n`
            + b.regel.replace(u[1], `/fonts/${slug(fam.name)}/${datei}`).replace(/\n\s*/g, "\n  ") + "\n\n";
  }
  bericht.push({ familie: fam.name, art: variabel ? "variabel" : "statisch", dateien: n, kb: Math.round(bytes / 1024) });
}

await mkdir(join("src", "app", "fonts"), { recursive: true });
await writeFile(join("src", "app", "fonts", "vendored.css"), cssOut);
console.table(bericht);
const f = bericht.filter((b) => b.fehler);
console.log(f.length ? `${f.length} FEHLER` : "alle Familien geladen");
console.log("gesamt:", bericht.reduce((s, b) => s + (b.kb || 0), 0), "KB in",
            bericht.reduce((s, b) => s + (b.dateien || 0), 0), "Dateien");
