// Sibling copy module for FormRoi.tsx — lifted from `lang === "ru" ? … : …`
// ternary chains (Hebrew Localization Phase 4, Task 3). The validation
// messages keep their `{min}`/`{max}`/`{current}` tokens verbatim — the
// component still runs them through its own `tpl()` substitution helper, so
// these stay plain strings rather than becoming functions.
import type { Locale } from "@/lib/locale";
import { isLocale } from "@/lib/locale";

export const FORM_ROI_EN = {
  inputName: "Name",
  inputSurname: "Surname",
  inputPhone: "Phone",
  inputEmail: "Email",
  buttonText: "Send calculation",
  successMessage: "We sent the calculation to your email and received a copy.",
  validationNameRequired: "Please enter your name",
  validationNameTooShort: "Minimum {min} characters. Current: {current}.",
  validationNameTooLong: "Maximum {max} characters. Current: {current}.",
  validationSurnameRequired: "Please enter your surname",
  validationSurnameTooShort: "Minimum {min} characters. Current: {current}.",
  validationSurnameTooLong: "Maximum {max} characters. Current: {current}.",
  validationPhoneRequired: "Please enter your phone number",
  validationPhoneTooShort: "Phone number is too short. Minimum {min}.",
  validationPhoneTooLong: "Phone number is too long. Maximum {max}.",
  validationPhoneInvalid: "Invalid phone number",
  validationEmailInvalid: "Invalid email address",
  validationEmailRequired: "Please enter your email",
  validationAgreementRequired: "Please confirm consent",
  validationAgreementOneOf: "You must accept the policy",
  contactMethodRequired: "What’s the best way to contact you?",
  contactMethodLegend: "What’s the best way to contact you?",
  phoneCallLabel: "Phone call",
  emailRadioLabel: "Email",
};

export const FORM_ROI_COPY: Record<Locale, typeof FORM_ROI_EN> = {
  en: FORM_ROI_EN,
  de: {
    inputName: "Vorname",
    inputSurname: "Nachname",
    inputPhone: "Telefon",
    inputEmail: "E-Mail",
    buttonText: "Berechnung senden",
    successMessage:
      "Wir haben die Berechnung an Ihre E-Mail-Adresse gesendet und eine Kopie erhalten.",
    validationNameRequired: "Bitte Namen eingeben",
    validationNameTooShort: "Mindestens {min} Zeichen. Aktuell: {current}.",
    validationNameTooLong: "Maximal {max} Zeichen. Aktuell: {current}.",
    validationSurnameRequired: "Bitte Nachnamen eingeben",
    validationSurnameTooShort: "Mindestens {min} Zeichen. Aktuell: {current}.",
    validationSurnameTooLong: "Maximal {max} Zeichen. Aktuell: {current}.",
    validationPhoneRequired: "Bitte Telefonnummer eingeben",
    validationPhoneTooShort: "Telefonnummer zu kurz. Minimum {min}.",
    validationPhoneTooLong: "Telefonnummer zu lang. Maximum {max}.",
    validationPhoneInvalid: "Ungültige Telefonnummer",
    validationEmailInvalid: "Ungültige E-Mail-Adresse",
    validationEmailRequired: "Bitte E-Mail eingeben",
    validationAgreementRequired: "Bitte Zustimmung bestätigen",
    validationAgreementOneOf: "Bitte akzeptieren Sie die Richtlinie",
    contactMethodRequired: "Wie können wir Sie am besten kontaktieren?",
    contactMethodLegend: "Wie können wir Sie am besten kontaktieren?",
    phoneCallLabel: "Anruf",
    emailRadioLabel: "E-Mail",
  },
  pl: {
    inputName: "Imię",
    inputSurname: "Nazwisko",
    inputPhone: "Telefon",
    inputEmail: "E-mail",
    buttonText: "Wyślij kalkulację",
    successMessage: "Wysłaliśmy kalkulację na Twój e-mail i otrzymaliśmy jej kopię.",
    validationNameRequired: "Wpisz imię",
    validationNameTooShort: "Minimum {min} znaków. Obecnie: {current}.",
    validationNameTooLong: "Maksymalnie {max} znaków. Obecnie: {current}.",
    validationSurnameRequired: "Wpisz nazwisko",
    validationSurnameTooShort: "Minimum {min} znaków. Obecnie: {current}.",
    validationSurnameTooLong: "Maksymalnie {max} znaków. Obecnie: {current}.",
    validationPhoneRequired: "Wpisz numer telefonu",
    validationPhoneTooShort: "Numer jest za krótki. Minimum {min}.",
    validationPhoneTooLong: "Numer jest za długi. Maksimum {max}.",
    validationPhoneInvalid: "Nieprawidłowy numer telefonu",
    validationEmailInvalid: "Nieprawidłowy adres e-mail",
    validationEmailRequired: "Wpisz e-mail",
    validationAgreementRequired: "Potwierdź zgodę",
    validationAgreementOneOf: "Musisz zaakceptować politykę",
    contactMethodRequired: "Wybierz preferowaną formę kontaktu",
    contactMethodLegend: "W jaki sposób najlepiej się z Tobą skontaktować?",
    phoneCallLabel: "Telefonicznie",
    emailRadioLabel: "E-mail",
  },
  ru: {
    inputName: "Имя",
    inputSurname: "Фамилия",
    inputPhone: "Телефон",
    inputEmail: "Email",
    buttonText: "Отправить расчет",
    successMessage: "Мы отправили расчет вам на email и получили его копию.",
    validationNameRequired: "Введите имя",
    validationNameTooShort: "Минимум {min} символа(ов). Сейчас: {current}.",
    validationNameTooLong: "Максимум {max} символов. Сейчас: {current}.",
    validationSurnameRequired: "Введите фамилию",
    validationSurnameTooShort: "Минимум {min} символа(ов). Сейчас: {current}.",
    validationSurnameTooLong: "Максимум {max} символов. Сейчас: {current}.",
    validationPhoneRequired: "Введите номер телефона",
    validationPhoneTooShort: "Номер слишком короткий. Минимум {min}.",
    validationPhoneTooLong: "Номер слишком длинный. Максимум {max}.",
    validationPhoneInvalid: "Некорректный номер телефона",
    validationEmailInvalid: "Некорректный email",
    validationEmailRequired: "Введите email",
    validationAgreementRequired: "Подтвердите согласие",
    validationAgreementOneOf: "Необходимо принять политику",
    contactMethodRequired: "Как с вами лучше связаться?",
    contactMethodLegend: "Как с вами лучше связаться?",
    phoneCallLabel: "Телефон",
    emailRadioLabel: "Email",
  },
  // Labels, the three "יש להזין …" required messages, the consent pair and the
  // contact-method question are word-identical with FormStatic/FormFull/
  // FormPartners (styleguide §11.6); the length messages reuse the
  // `לפחות {min} תווים` / `עד {max} תווים` pattern fixed in WP1.
  he: {
    inputName: "שם פרטי",
    inputSurname: "שם משפחה",
    inputPhone: "טלפון",
    inputEmail: "אימייל",
    buttonText: "שליחת החישוב",
    successMessage: "שלחנו את החישוב לאימייל שלכם וקיבלנו עותק אצלנו.",
    validationNameRequired: "יש להזין שם פרטי",
    validationNameTooShort: "לפחות {min} תווים. כרגע: {current}.",
    validationNameTooLong: "עד {max} תווים. כרגע: {current}.",
    validationSurnameRequired: "יש להזין שם משפחה",
    validationSurnameTooShort: "לפחות {min} תווים. כרגע: {current}.",
    validationSurnameTooLong: "עד {max} תווים. כרגע: {current}.",
    validationPhoneRequired: "יש להזין טלפון",
    validationPhoneTooShort: "מספר הטלפון קצר מדי. לפחות {min} תווים.",
    validationPhoneTooLong: "מספר הטלפון ארוך מדי. עד {max} תווים.",
    validationPhoneInvalid: "מספר טלפון לא תקין",
    validationEmailInvalid: "כתובת אימייל לא תקינה",
    validationEmailRequired: "יש להזין אימייל",
    validationAgreementRequired: "נדרש אישור",
    validationAgreementOneOf: "חובה לאשר",
    contactMethodRequired: "מה דרך ההתקשרות הנוחה לכם?",
    contactMethodLegend: "מה דרך ההתקשרות הנוחה לכם?",
    phoneCallLabel: "שיחת טלפון",
    emailRadioLabel: "אימייל",
  }, // REVIEW(he)
};

export const formRoiCopy = (lang: string) => FORM_ROI_COPY[isLocale(lang) ? lang : "en"];
