// Heuristic legacy-Project <-> Development name matches from MERGE_AUDIT.md
// §4 ("Legacy Project ↔ Development overlap table"), generated by normalized-
// token Jaccard similarity on name — NOT a verified real-world identity match.
// Frozen, one-time list from that audit (2026-07-15); it is not regenerated
// live. A human must confirm or reject each row here before any
// activate/deactivate/redirect logic acts on it (see Phase 5.2-5.5 in the
// original merge plan, and DEPLOYMENT.md).
//
// The 5 Developments the audit found with no legacy counterpart at all
// ("None found" — venus-ridge-villas, prodromi-modern-living, city-gardens,
// kato-paphos-residences, blackpine) are omitted here: there's no legacy
// project to link against, so nothing to confirm or reject.
export type OverlapCandidate = {
  legacySlug: string;
  legacyTitle: string;
  developmentSlug: string;
  developmentName: string;
  confidence: "High" | "Medium" | "Low-Medium" | "Likely false positive";
  note?: string;
};

export const OVERLAP_CANDIDATES: OverlapCandidate[] = [
  { legacySlug: "cypress-groove-bbf", legacyTitle: "Cypress Grove", developmentSlug: "cypress-grove", developmentName: ":cypress grove", confidence: "High" },
  { legacySlug: "riverside-domenica", legacyTitle: "Riverside", developmentSlug: "riverside", developmentName: "riverside", confidence: "High" },
  { legacySlug: "galaxy-residences-aristo", legacyTitle: "Galaxy Residences", developmentSlug: "grand-residences", developmentName: "Galaxy Residences", confidence: "High" },
  { legacySlug: "eden-golf-bbf", legacyTitle: "Eden Golf", developmentSlug: "golf-residences", developmentName: "Eden Golf", confidence: "High" },
  { legacySlug: "luma-genesis", legacyTitle: "Luma Genesis", developmentSlug: "luma-genesis", developmentName: "Luma Genesis", confidence: "High", note: "slug-identical" },
  { legacySlug: "noble-apartments", legacyTitle: "Noble Apartments", developmentSlug: "noble", developmentName: "Noble", confidence: "High" },
  { legacySlug: "oculus-domenica", legacyTitle: "Oculus", developmentSlug: "oculus", developmentName: "oculus", confidence: "High" },
  { legacySlug: "quatrro", legacyTitle: "QUATRRO", developmentSlug: "quatrro", developmentName: "Quatrro", confidence: "High", note: "slug-identical" },
  { legacySlug: "velaro-homes", legacyTitle: "Velaro Homes", developmentSlug: "velaro-homes", developmentName: "Velaro Homes", confidence: "High", note: "slug-identical" },
  { legacySlug: "neon-homes-oli", legacyTitle: "Neon Homes", developmentSlug: "neon-homes", developmentName: "Neon Homes", confidence: "High" },
  { legacySlug: "lazzero-park", legacyTitle: "Lazzero Park", developmentSlug: "lazzero-park", developmentName: "Lazzero Park", confidence: "High", note: "slug-identical" },
  { legacySlug: "celestia-island-blue", legacyTitle: "Celestia", developmentSlug: "celestia", developmentName: "Celestia", confidence: "High" },
  { legacySlug: "aion-ku", legacyTitle: "Aion", developmentSlug: "aion", developmentName: "Aion", confidence: "High" },
  { legacySlug: "emerald-park-luma", legacyTitle: "Emerald Park", developmentSlug: "emerald-park", developmentName: "Emerald Park", confidence: "High" },
  { legacySlug: "pearl-park-aristo", legacyTitle: "Pearl Park Residences", developmentSlug: "universal-park-residences", developmentName: "Pearl Park Residences", confidence: "High" },
  { legacySlug: "avrora-court-aristo", legacyTitle: "Avora Court", developmentSlug: "aurora-residence", developmentName: "Avora Court", confidence: "High" },
  { legacySlug: "imperial-residences-aristo", legacyTitle: "Imperial Residences", developmentSlug: "magestic-residences", developmentName: "Imperial Residences", confidence: "High" },
  { legacySlug: "royal-residences-aristo", legacyTitle: "Royal Residences", developmentSlug: "king-residences", developmentName: "Royal Residences", confidence: "High" },
  { legacySlug: "andriana-court-aristo", legacyTitle: "Andriana Court", developmentSlug: "city-living-court", developmentName: "Andriana Court", confidence: "High" },
  { legacySlug: "ppremier-residences-aristo", legacyTitle: "Premier Residences", developmentSlug: "venus-rock-residences", developmentName: "Premier Residences", confidence: "High" },
  { legacySlug: "pelagos-beachfront-villas-aristo", legacyTitle: "Pelagos Beachfront Villas", developmentSlug: "chloraka-beachfront-villas", developmentName: "Azure Beachfront Villas", confidence: "Medium", note: "different qualifier word (\"Pelagos\" vs \"Azure\") — verify same building" },
  { legacySlug: "azalea-apartments", legacyTitle: "Azalea Apartments", developmentSlug: "universal-villas", developmentName: "Azalea Villas", confidence: "Medium", note: "\"Apartments\" vs \"Villas\" — verify same building" },
  { legacySlug: "eniko-mare-domenica", legacyTitle: "Eniko Mare", developmentSlug: "eniko-mare", developmentName: "apartments-in-paphos-eniko-mare", confidence: "Medium" },
  { legacySlug: "aquamarine-villas-aristo", legacyTitle: "Aquamarine Villas", developmentSlug: "sunny-coastal-residences", developmentName: "Aquamarine Coastal Villas", confidence: "Medium" },
  { legacySlug: "begonia-residences-aristo", legacyTitle: "Begonia Residences", developmentSlug: "chloraka-residences", developmentName: "Melania - Begonia Residences", confidence: "Medium" },
  { legacySlug: "meteora-residences-aristo", legacyTitle: "Meteora Residences", developmentSlug: "meteora-residences", developmentName: "Meteora Residential Development", confidence: "Low-Medium" },
  { legacySlug: "kamares-village", legacyTitle: "Kamares Village", developmentSlug: "neo-chorio-villas-1", developmentName: "Agnades Village 1", confidence: "Likely false positive", note: "matched only on generic \"village\" token, different specific names" },
  { legacySlug: "kamares-village", legacyTitle: "Kamares Village", developmentSlug: "argaka-villa", developmentName: "Argaka Village 6", confidence: "Likely false positive", note: "same reason" },
  { legacySlug: "pearl-sea-caves-villa-1-island-blue", legacyTitle: "Pearl Sea Caves Villa 1", developmentSlug: "chloraka-rose-residences", developmentName: "Roseland Villas 1", confidence: "Likely false positive" },

  // 2026-08-03 addition — a second sweep (title + developer-feed-account
  // match, run after the azalea-villas/serenity-court sold-out cutover
  // surfaced them as an unlinked duplicate) found these 20 candidates the
  // 2026-07-15 audit missed. Same rule as above: appearing here does NOT
  // link or archive anything — a human still confirms/rejects each row via
  // the overlaps UI. Deliberately excludes 3 exact-title matches with a
  // DIFFERING developer (premier-residences-domenica/premier-residences,
  // montville-sol/montville, riverside-residences-island-blue/riverside) —
  // those need manual research into whether it's a real developer handover
  // or two different buildings sharing a generic name, not a quick
  // confirm/reject pass.
  { legacySlug: "viewpoint-hills-aristo", legacyTitle: "Viewpoint Hills", developmentSlug: "viewpoint-hills", developmentName: "Viewpoint Hills", confidence: "High", note: "2026-08-03 sweep: exact title + same Aristo feed account, same pattern as azalea-villas/serenity-court" },
  { legacySlug: "villa-superior-aristo", legacyTitle: "Villa Superior", developmentSlug: "villa-superior", developmentName: "Villa Superior", confidence: "High", note: "2026-08-03 sweep: exact title + same Aristo feed account" },
  { legacySlug: "zephyros-village-3-aristo", legacyTitle: "Zephyros Village 3", developmentSlug: "zephyros-village-3", developmentName: "Zephyros Village 3", confidence: "High", note: "2026-08-03 sweep: exact title + same Aristo feed account" },
  { legacySlug: "elementa-domenica", legacyTitle: "Elements", developmentSlug: "elements", developmentName: "Elements", confidence: "High", note: "2026-08-03 sweep: exact title + same Domenica feed account" },
  { legacySlug: "konia-aura-domenica", legacyTitle: "Konia Aura", developmentSlug: "aura-konia", developmentName: "Konia Aura", confidence: "High", note: "2026-08-03 sweep: exact title + same Domenica feed account" },
  { legacySlug: "la-bella-domenica", legacyTitle: "La Bella", developmentSlug: "la-bella", developmentName: "La Bella", confidence: "High", note: "2026-08-03 sweep: exact title + same Domenica feed account" },
  { legacySlug: "morea-residences-inex", legacyTitle: "Morea Residences", developmentSlug: "morea-residences", developmentName: "Morea Residences", confidence: "High", note: "2026-08-03 sweep: exact title + same INEX feed account" },
  { legacySlug: "qube-inex", legacyTitle: "Qube", developmentSlug: "qube", developmentName: "Qube", confidence: "High", note: "2026-08-03 sweep: exact title + same INEX feed account" },
  { legacySlug: "rosa-dei-venti-bbf", legacyTitle: "Rosa Dei Venti", developmentSlug: "rosa-dei-venti", developmentName: "Rosa dei Venti", confidence: "Medium", note: "2026-08-03 sweep: exact title, developer text \"BBF\" on both sides — developer-account link not resolved programmatically, verify manually" },
  { legacySlug: "salt-bbf", legacyTitle: "Salt", developmentSlug: "salt", developmentName: "Salt", confidence: "Medium", note: "2026-08-03 sweep: exact title, developer text \"BBF\" on both sides" },
  { legacySlug: "sense-bbf", legacyTitle: "Sense", developmentSlug: "sense", developmentName: "Sense", confidence: "Medium", note: "2026-08-03 sweep: exact title, developer text \"BBF\" on both sides" },
  { legacySlug: "spirit-bbf", legacyTitle: "Spirit", developmentSlug: "spirit", developmentName: "Spirit", confidence: "Medium", note: "2026-08-03 sweep: exact title, developer text \"BBF\" on both sides" },
  { legacySlug: "verde-bbf", legacyTitle: "Verde", developmentSlug: "verde", developmentName: "Verde", confidence: "Medium", note: "2026-08-03 sweep: exact title, developer text \"BBF\" on both sides" },
  { legacySlug: "vision-bbf", legacyTitle: "Vision", developmentSlug: "vision", developmentName: "Vision", confidence: "Medium", note: "2026-08-03 sweep: exact title, developer text \"BBF\" on both sides" },
  { legacySlug: "synergy-bbf", legacyTitle: "Synergy", developmentSlug: "synergy", developmentName: "Synergy", confidence: "Medium", note: "2026-08-03 sweep: exact title, developer text \"BBF\" on both sides, same district (Larnaca)" },
  { legacySlug: "rise-bbf", legacyTitle: "Rise", developmentSlug: "rise", developmentName: "Rise", confidence: "Medium", note: "2026-08-03 sweep: exact title, developer text \"BBF\" on both sides" },
  { legacySlug: "nest-bbf", legacyTitle: "Nest", developmentSlug: "nest", developmentName: "Nest", confidence: "Medium", note: "2026-08-03 sweep: exact title, developer text \"BBF\" on both sides" },
  { legacySlug: "life-bbf", legacyTitle: "Life", developmentSlug: "life", developmentName: "Life", confidence: "Medium", note: "2026-08-03 sweep: exact title, developer text \"BBF\" on both sides" },
  { legacySlug: "glow-bbf", legacyTitle: "Glow", developmentSlug: "glow", developmentName: "Glow", confidence: "Medium", note: "2026-08-03 sweep: exact title, developer text \"BBF\" on both sides — a second Development (\"Glow 2\") also exists, likely a distinct later phase, not this match" },
  { legacySlug: "eden-bay-bbf", legacyTitle: "Eden Bay", developmentSlug: "eden-bay", developmentName: "Eden Bay", confidence: "Medium", note: "2026-08-03 sweep: exact title, developer text \"BBF\" on both sides" },
];
